# Basic Information
title: Single-Shot Domain Adaptation via target-aware generative augmentations

authors:
  - name: Rakshith Subramanyam
    link: https://www.example.com/rakshith
    equal_contrib: true
    affiliations: [1]
  - name: Kowshik Thopalli
    link: https://kowshikthopalli.github.io/
    equal_contrib: true
    affiliations: [1]
  - name: Spring Berman
    link: https://search.asu.edu/profile/1943720
    affiliations: [2]
  - name: Pavan Turaga
    link: https://pavanturaga.com/
    affiliations: [1, 2]
  - name: Jayaraman J. Thiagarajan
    link: https://jjthiagarajan.com/
    affiliations: [1]

affiliations:
  - symbol: 1
    name: Arizona State University
    link: https://www.asu.edu/
  - symbol: 2
    name: Lawrence Livermore National Laboratory
    link: https://www.llnl.gov/


conference: 2023 IEEE International Conference on Acoustics, Speech, and Signal Processing (ICASSP 2023), 

# Search Engine Optimization (SEO)
keywords: Single-Shot Domain Adaptation, Generative Augmentations, Domain Adaptation,SiSTA
canonical: https://rakshithsubramanyam.github.io/
description: This paper proposes a novel single-shot domain adaptation method that leverages target-aware generative augmentations to improve the performance of the source model on the target domain.

# Links
paper_link: ./assets/files/paper.pdf
slides_link: https://www.linkedin.com/
poster_link: https://www.linkedin.com/
video_link: https://www.linkedin.com/
github_link: https://github.com/kowshikthopalli/SISTA

# Images
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: false

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
