- src: "assets/img/pipeline_a.png"
  caption: 
  alt: "Alt text 1"

- src: "assets/img/pipeline_b.png"
  caption: 
  alt: "Alt text 2"

- src: "assets/img/pipeline_c.png"
  caption: 
  alt: "Alt text 3"

- src: "assets/img/pipeline_d.png"
  caption: 
  alt: "Alt text 4"
